# Generated by Django 3.2.3 on 2022-01-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='classification',
            field=models.CharField(choices=[('PharmaceuticalDrugs', 'PharmaceuticalDrugs'), ('Tradomedicals', 'Tradomedicals'), ('skincare', 'skincare')], max_length=300, null=True),
        ),
    ]
