# Generated by Django 3.2.3 on 2022-01-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0002_products_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=30)),
                ('Quantity', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Phone', models.CharField(max_length=30)),
                ('customers_address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('Tel', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
