# Generated by Django 3.2.3 on 2022-01-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0004_auto_20220125_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='classification',
            new_name='status',
        ),
    ]
