# Generated by Django 3.2.3 on 2022-02-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0005_rename_classification_products_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_orders',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer_orders',
            name='customer_name',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharma_app.customers'),
        ),
        migrations.AlterField(
            model_name='customer_orders',
            name='product_name',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharma_app.products'),
        ),
    ]
