# Generated by Django 3.2.3 on 2022-02-12 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0006_auto_20220212_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_orders',
            name='customer_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='adminEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Out for Delivery', 'Out for Delivery'), ('Pending', 'Pending')], max_length=30, null=True)),
                ('Quantity', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Phone', models.CharField(max_length=30)),
                ('customers_address', models.CharField(max_length=30)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('Item', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharma_app.products')),
            ],
        ),
    ]
