# Generated by Django 3.2.3 on 2022-02-13 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0007_auto_20220212_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminentry',
            name='customer_firstname',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharma_app.customers'),
        ),
    ]
