# Generated by Django 3.2.3 on 2022-02-15 20:29

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0009_alter_customer_orders_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_orders',
            name='customer_name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=30),
        ),
    ]
