# Generated by Django 3.2.3 on 2022-02-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0010_alter_customer_orders_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_orders',
            old_name='Phone',
            new_name='Email',
        ),
        migrations.AlterField(
            model_name='customer_orders',
            name='customer_name',
            field=models.CharField(max_length=30),
        ),
    ]
