# Generated by Django 3.2.3 on 2022-02-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0012_customers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='profile_Pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
